
#INCLUDE "MAIN.H"
#INCLUDE "GPIO.H"

VOID SYSTEMCLOCK_CONFIG(VOID);

INT MAIN(VOID)
{

  HAL_INIT();
  SYSTEMCLOCK_CONFIG();
  MX_GPIO_INIT();

  WHILE (1)
  {
    /* USER CODE END WHILE */
	  HAL_GPIO_WRITEPIN(	GPIOC,GPIO_PIN_13,1);
	  HAL_DELAY(100);
	  HAL_GPIO_WRITEPIN(	GPIOC,GPIO_PIN_13,0);
	  HAL_DELAY(100);

    /* USER CODE BEGIN 3 */
  }

}

VOID SYSTEMCLOCK_CONFIG(VOID)
{
  RCC_OSCINITTYPEDEF RCC_OSCINITSTRUCT = {0};
  RCC_CLKINITTYPEDEF RCC_CLKINITSTRUCT = {0};

  /** INITIALIZES THE RCC OSCILLATORS ACCORDING TO THE SPECIFIED PARAMETERS
  * IN THE RCC_OSCINITTYPEDEF STRUCTURE.
  */
  RCC_OSCINITSTRUCT.OSCILLATORTYPE = RCC_OSCILLATORTYPE_HSI;
  RCC_OSCINITSTRUCT.HSISTATE = RCC_HSI_ON;
  RCC_OSCINITSTRUCT.HSICALIBRATIONVALUE = RCC_HSICALIBRATION_DEFAULT;
  RCC_OSCINITSTRUCT.PLL.PLLSTATE = RCC_PLL_NONE;
  IF (HAL_RCC_OSCCONFIG(&RCC_OSCINITSTRUCT) != HAL_OK)
  {
    ERROR_HANDLER();
  }

  /** INITIALIZES THE CPU, AHB AND APB BUSES CLOCKS
  */
  RCC_CLKINITSTRUCT.CLOCKTYPE = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_CLKINITSTRUCT.SYSCLKSOURCE = RCC_SYSCLKSOURCE_HSI;
  RCC_CLKINITSTRUCT.AHBCLKDIVIDER = RCC_SYSCLK_DIV1;
  RCC_CLKINITSTRUCT.APB1CLKDIVIDER = RCC_HCLK_DIV1;
  RCC_CLKINITSTRUCT.APB2CLKDIVIDER = RCC_HCLK_DIV1;

  IF (HAL_RCC_CLOCKCONFIG(&RCC_CLKINITSTRUCT, FLASH_LATENCY_0) != HAL_OK)
  {
    ERROR_HANDLER();
  }
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @BRIEF  THIS FUNCTION IS EXECUTED IN CASE OF ERROR OCCURRENCE.
  * @RETVAL NONE
  */
VOID ERROR_HANDLER(VOID)
{
  /* USER CODE BEGIN ERROR_HANDLER_DEBUG */
  /* USER CAN ADD HIS OWN IMPLEMENTATION TO REPORT THE HAL ERROR RETURN STATE */
  __DISABLE_IRQ();
  WHILE (1)
  {
  }
}

#IFDEF  USE_FULL_ASSERT
/**
  * @BRIEF  REPORTS THE NAME OF THE SOURCE FILE AND THE SOURCE LINE NUMBER
  *         WHERE THE ASSERT_PARAM ERROR HAS OCCURRED.
  * @PARAM  FILE: POINTER TO THE SOURCE FILE NAME
  * @PARAM  LINE: ASSERT_PARAM ERROR LINE SOURCE NUMBER
  * @RETVAL NONE
  */
VOID ASSERT_FAILED(UINT8_T *FILE, UINT32_T LINE)
{
  /* USER CODE BEGIN 6 */
  /* USER CAN ADD HIS OWN IMPLEMENTATION TO REPORT THE FILE NAME AND LINE NUMBER,
     EX: PRINTF("WRONG PARAMETERS VALUE: FILE %S ON LINE %D\R\N", FILE, LINE) */
  /* USER CODE END 6 */
}
#ENDIF /* USE_FULL_ASSERT */
